---
services:
  postgres:
    container_name: gatus-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 300
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - gatus-postgres:/var/lib/postgresql/data
    networks:
      - gatus

  gatus:
    container_name: gatus
    image: twinproduction/gatus:v5.35.0
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_ENDPOINT=postgres:5432
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
    volumes:
      - /home/hughboi/code/gatus/config:/config:ro
    dns:
      - "10.10.10.8"
      - "10.10.10.10"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gatus.entrypoints=http"
      - "traefik.http.routers.gatus.rule=Host(`gatus.hughboi.cc`)"
      - "traefik.http.middlewares.gatus-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.gatus.middlewares=gatus-https-redirect"
      - "traefik.http.routers.gatus-secure.entrypoints=https"
      - "traefik.http.routers.gatus-secure.rule=Host(`gatus.hughboi.cc`)"
      - "traefik.http.routers.gatus-secure.tls=true"
      - "traefik.http.services.gatus.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - gatus


volumes:
  gatus-postgres:

networks:
  proxy:
    external: true
  gatus:
