apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
        - name: searxng
          image: searxng/searxng:2026.6.8-f3fab143b
          ports:
            - containerPort: 8080
          env:
            - name: SEARXNG_BASE_URL
              value: "https://search.hughboi.cc/"
            - name: UWSGI_WORKERS
              value: "4"
            - name: UWSGI_THREADS
              value: "4"
          securityContext:
            capabilities:
              add:
                - CHOWN
                - SETGID
                - SETUID
                - FOWNER
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /etc/searxng
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: searxng-config
