- Servers:

    - pve-srv-1:
        href: https://10.10.10.1:8006
        description: 10.10.10.1:8006
        siteMonitor: https://10.10.10.1:8006
        icon: proxmox.png
        widget:
            type: proxmox
            url: https://10.10.10.1:8006
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: pve-srv-1
            fields: ["vms", "resources.cpu", "resources.mem"]

    - pve-srv-2:
        href: https://10.10.10.2:8006
        description: 10.10.10.2:8006
        siteMonitor: https://10.10.10.2:8006
        icon: proxmox.png
        widget:
            type: proxmox
            url: https://10.10.10.2:8006
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: pve-srv-2
            fields: ["vms", "resources.cpu", "resources.mem"]

    - pve-srv-3:
        href: https://10.10.10.3:8006
        description: 10.10.10.3:8006
        siteMonitor: https://10.10.10.3:8006
        icon: proxmox.png
        widget:
            type: proxmox
            url: https://10.10.10.3:8006
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: pve-srv-3
            fields: ["vms", "resources.cpu", "resources.mem"]

    - pve-srv-4:
        href: https://10.10.10.4:8006
        description: 10.10.10.4:8006
        siteMonitor: https://10.10.10.4:8006
        icon: proxmox.png
        widget:
            type: proxmox
            url: https://10.10.10.4:8006
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: pve-srv-4
            fields: ["vms", "resources.cpu", "resources.mem"]

- Management:

    - Adguard:
        href: https://adguard.hughboi.cc
        #description: DNS
        siteMonitor: https://adguard.hughboi.cc
        icon: adguard-home.png

    - Gitea:
        href: https://gitea.hughboi.cc
        siteMonitor: https://gitea.hughboi.cc
        icon: gitea.png

    - Pocket ID:
        href: https://pocket.hughboi.cc
        siteMonitor: https://pocket.hughboi.cc
        icon: pocket-id-light.png

    - Portainer:
        href: https://portainer.hughboi.cc
        siteMonitor: https://portainer.hughboi.cc
        icon: portainer.png

    - Rancher:
        href: https://10.10.30.61:443
        siteMonitor: https://10.10.30.61:443
        icon: rancher.png

    - Traefik:
        href: https://traefik.hughboi.cc
        siteMonitor: https://traefik.hughboi.cc
        icon: traefik.png

    - Unifi:
        href: https://10.10.10.10:8443
        siteMonitor: https://10.10.10.10:8443
        icon: unifi.png

    - Wazuh:
        href: https://wazuh.hughboi.cc
        siteMonitor: https://wazuh.hughboi.cc
        icon: wazuh.png

- Personal:

    - ezBookKeeping:
        href: https://bookkeeping.hughboi.cc
        siteMonitor: https://bookkeeping.hughboi.cc
        icon: ezbookkeeping.png

    - Fasten Health:
        href: https://fastenhealth.hughboi.cc
        siteMonitor: https://fastenhealth.hughboi.cc
        icon: fasten-health.svg

    - FreshRSS:
        href: https://freshrss.hughboi.cc
        icon: freshrss.png
        siteMonitor: https://freshrss.hughboi.cc

    - Hoarder:
        href: https://hoarder.hughboi.cc
        siteMonitor: https://hoarder.hughboi.cc
        icon: hoarder.png

    - Mealie:
        href: https://mealie.hughboi.cc
        siteMonitor: https://mealie.hughboi.cc
        icon: mealie.png

    - SearXNG:
        href: https://search.hughboi.cc
        siteMonitor: https://search.hughboi.cc
        icon: searxng.png

    - Vaultwarden:
        href: https://vaultwarden.hughboi.cc
        siteMonitor: https://vaultwarden.hughboi.cc
        icon: vaultwarden-light.png

- Media:

    - Immich:
        href: https://immich.hughboi.cc
        siteMonitor: https://immich.hughboi.cc
        icon: immich.png

    - Jellyfin:
        href: https://jellyfin.hughboi.cc
        icon: jellyfin.png
        siteMonitor: https://jellyfin.hughboi.cc

    - Paperless-ngx:
        href: https://paperless.hughboi.cc
        siteMonitor: https://paperless.hughboi.cc
        icon: paperless.png

    - Romm:
        href: https://romm.hughboi.cc
        siteMonitor: https://romm.hughboi.cc
        icon: romm.png

    - YT Archive:
        href: https://yt.hughboi.cc
        icon: youtube.png
        siteMonitor: https://yt.hughboi.cc

- Automation:

    - Home Assistant:
        href: https://home-assistant.hughboi.cc
        siteMonitor: https://home-assistant.hughboi.cc
        icon: home-assistant.png

    - n8n:
        href: https://n8n.hughboi.cc
        siteMonitor: https://n8n.hughboi.cc
        icon: n8n.png

    - Ntfy:
        href: https://ntfy.hughboi.cc
        siteMonitor: https://ntfy.hughboi.cc
        icon: ntfy.png

    - Semaphore:
        href: https://semaphore.hughboi.cc
        siteMonitor: https://semaphore.hughboi.cc
        icon: semaphore.png

    - Syncthing:
        href: https://syncthing.hughboi.cc
        siteMonitor: https://syncthing.hughboi.cc
        icon: syncthing.svg

- Monitoring:

    - Gatus:
        href: https://gatus.hughboi.cc
        siteMonitor: https://gatus.hughboi.cc
        icon: gatus.png

    - Glances:
        href: http://10.10.10.10:61208/
        siteMonitor: http://10.10.10.10:61208/
        icon: glances.png

    - Grafana:
        href: https://grafana.hughboi.cc
        siteMonitor: https://grafana.hughboi.cc
        icon: grafana.png

    - InfluxDB:
        href: https://influxdb.hughboi.cc
        siteMonitor: https://influxdb.hughboi.cc
        icon: influxdb.png

    - Prometheus:
        href: http://10.10.10.10:9070
        siteMonitor: http://10.10.10.10:9070
        icon: prometheus

    # ### GLANCES
    # - Processes:
    #     href: http://10.10.10.10:61208
    #     widget:
    #         type: glances
    #         url: http://10.10.10.10:61208
    #         metric: process
    #         version: 4
    #         chart: true
    # - CPU:
    #     href: http://10.10.10.10:61208
    #     widget:
    #         type: glances
    #         url: http://10.10.10.10:61208
    #         metric: cpu
    #         version: 4
    #         chart: true
    # - Memory:
    #     href: http://10.10.10.10:61208
    #     widget:
    #         type: glances
    #         url: http://10.10.10.10:61208
    #         metric: memory
    #         version: 4
    #         chart: true
    # - NVME:
    #     href: http://10.10.10.10:61208
    #     widget:
    #         type: glances
    #         url: http://10.10.10.10:61208
    #         metric: disk:sda
    #         version: 4
    #         chart: true

- Storage:

    - Filebrowser:
        href: https://file.hughboi.cc
        siteMonitor: https://file.hughboi.cc
        icon: filebrowser.png

    - Longhorn:
        href: https://10.10.30.61/k8s/clusters/local/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/
        siteMonitor: https://10.10.30.61/k8s/clusters/local/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/
        icon: longhorn.svg

    - PBS:
        href: https://10.10.10.6:8007
        siteMonitor: https://10.10.10.6:8007
        icon: proxmox.png

    - Synology:
        href: http://10.10.10.15:5000
        siteMonitor: http://10.10.10.15:5000
        icon: synology.png

    - TrueNAS:
        href: https://10.10.10.5
        siteMonitor: https://10.10.10.5
        icon: truenas.png

- Calendar:

    - _:
        widget:
            type: calendar
            firstDayInWeek: sunday
            view: agenda # optional - possible values monthly, agenda
            maxEvents: 6
            showTime: true
            timezone: America/Denver
            integrations:
                - type: ical
                  url: ${HOMEPAGE_VAR_GOOGLE_CALENDAR}
                  name: Google
                  color: zinc
                  params: # optional - additional params for the service
                    showName: true # optional - show name before event title in event line - defaults to false

                - type: ical
                  url: ${HOMEPAGE_VAR_ICLOUD_CALENDAR}
                  name: iCloud
                  color: zinc
                  params: # optional - additional params for the service
                    showName: true # optional - show name before event title in event line - defaults to false
