apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-data
  namespace: gatus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
