---
secrets:
  cf_api_token:
    file: /home/hughboi/data/traefik/cf_api_token.txt   # create and paste CF API token

services:
  traefik:
    container_name: traefik
    image: traefik:v3.6.6
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    environment:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf_api_token
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
    secrets:
      - cf_api_token
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/hughboi/code/traefik/data/traefik.yml:/traefik.yml:ro
      - /home/hughboi/data/traefik/data/acme.json:/acme.json
      - /home/hughboi/code/traefik/data/config.yml:/config.yml:ro
      - /home/hughboi/data/traefik/logs:/var/log/traefik
    ports:
      - "80:80"
      - "443:443"
      # - "443:443/tcp"   # Uncomment for HTTP/3
      # - "443:443/udp"   # Uncomment for HTTP/3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.hughboi.cc`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.hughboi.cc`)"
      # - "traefik.http.routers.traefik-secure.middlewares=authentik"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=hughboi.cc"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.hughboi.cc"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.services.traefik.loadBalancer.server.port=8080"
      - "diun.enable=true"
    dns:
      - 10.10.10.8
      - 10.10.10.10
    networks:
      - proxy


networks:
  proxy:
    external: true
