unifi_networks:
  # --- Core Infrastructure ---
  management:
    vlan: 1
    subnet: "10.10.10.0/24"
    gateway: "10.10.10.254"
    dhcp_start: "10.10.10.100"
    dhcp_stop: "10.10.10.200"
    pxe_server: "10.10.99.99"
    pxe_file: "netboot.xyz.efi"

  # --- Internal High-Performance (No Gateway/DHCP) ---
  cluster:
    vlan: 2
    subnet: "10.10.20.0/24"
    dhcp_enabled: false

  storage:
    vlan: 4
    subnet: "10.10.40.0/24"
    dhcp_enabled: false

  # --- Routed App Networks ---
  k3s:
    vlan: 3
    subnet: "10.10.30.0/24"
    gateway: "10.10.30.254"

  vpn:
    vlan: 8
    subnet: "10.10.80.0/24"
    gateway: "10.10.80.254"

  torrent:
    vlan: 49
    subnet: "172.16.20.0/24"
    gateway: "172.16.20.254"

  provisioning:
    vlan: 99
    subnet: "10.10.99.0/24"
    gateway: "10.10.99.254"