apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-mysql
  namespace: semaphore
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-config
  namespace: semaphore
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
