services:
  hwaccel:
    devices:
      - /dev/dri:/dev/dri  # If using Intel QuickSync or VAAPI
  openvino:
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /dev/bus/usb:/dev/bus/usb
