apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hoarder-data
  namespace: hoarder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hoarder-meilisearch
  namespace: hoarder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
