apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbootxyz-config
  namespace: netbootxyz
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbootxyz-assets
  namespace: netbootxyz
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
