variable "dns_server_ip" {
  description = "IP of the host running BIND9 (Athena, 10.10.10.8)"
  type        = string
  default     = "10.10.10.8"
}

variable "tsig_key" {
  description = "Base64-encoded TSIG key secret generated by tsig-keygen (see README)"
  type        = string
  sensitive   = true
}
