apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fasten-health-db
  namespace: fasten-health
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fasten-health-cache
  namespace: fasten-health
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
