apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ezbookkeeping-mysql
  namespace: ezbookkeeping
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ezbookkeeping-storage
  namespace: ezbookkeeping
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
